-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 22:49:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema srevisiones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema srevisiones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `srevisiones` DEFAULT CHARACTER SET ucs2 COLLATE ucs2_spanish2_ci ;
USE `srevisiones` ;

-- -----------------------------------------------------
-- Table `srevisiones`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srevisiones`.`evaluacion` (
  `idevaluacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_eval` VARCHAR(50) NOT NULL,
  `fecha_eval` DATE NOT NULL,
  `cant_puntos` INT NOT NULL,
  `num_parcial` INT NOT NULL,
  `activa` TINYINT NOT NULL,
  PRIMARY KEY (`idevaluacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srevisiones`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srevisiones`.`estudiantes` (
  `idestudiantes` INT NOT NULL AUTO_INCREMENT,
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `apellido` VARCHAR(80) NOT NULL,
  `comentario` VARCHAR(255) NULL,
  `enlace` VARCHAR(80) NOT NULL,
  `num_parcial` INT NOT NULL,
  PRIMARY KEY (`idestudiantes`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srevisiones`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srevisiones`.`profesores` (
  `idprofesores` INT NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `contra` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idprofesores`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
